# Generated by Django 5.2.9 on 2026-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('rutracker_id', models.CharField(max_length=50, unique=True, verbose_name='ID раздачи')),
                ('size_readable', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('seeds', models.IntegerField(default=0, verbose_name='Сиды')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
