# Generated by Django 5.2.9 on 2026-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='rutracker_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='seeds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='size_readable',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
